# Generated by Django 2.0 on 2017-12-28 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug_name', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_main_phone', models.TextField(max_length=100)),
                ('contact_alternatove', models.TextField(max_length=100)),
            ],
        ),
    ]
