# Generated by Django 2.0 on 2017-12-29 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojomanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studant',
            old_name='contact_alternatove',
            new_name='contact_alternative',
        ),
    ]
