# Generated by Django 2.0 on 2018-01-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojomanager', '0003_auto_20180117_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
