# Generated by Django 2.0 on 2018-01-17 17:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojomanager', '0006_auto_20180117_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dias', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('forma_pagamento', models.CharField(choices=[(None, 'Escolha a forma de pagamento realizada'), ('Dinheiro', 'Dinheiro'), ('Deposito', 'Deposito'), ('Transferência', 'Trasferência bancária'), ('Cheque', 'Cheque'), ('Outros', 'Outros - Especificar')], max_length=20)),
                ('pagamento_referente_a', models.TextField(help_text='Colocar quais meses o pagamento é referente especificando o ano também')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojomanager.Pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='modalidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dojomanager.Modalidade'),
        ),
    ]
