# Generated by Django 2.0 on 2018-01-18 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojomanager', '0007_auto_20180117_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Telefone deve ser neste formato: '+999999999'. no máximo 15 digitos são permitidos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
