# Generated by Django 2.0 on 2018-01-21 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojomanager', '0010_auto_20180121_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to='dojomanager.Pessoa'),
        ),
    ]
